kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443
nodes:
- role: control-plane
  image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    # protect UI
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 31490
    hostPort: 31490
    listenAddress: "0.0.0.0"
    protocol: TCP
